### ISSUE TITLE
UID and GID not found, Can't Drop Privileges  (Arch Linux)

### ISSUE THREAD

**Issue by Harleythetech** [Ps3itaTeam/ps4fancontrol#1]
I'm trying to make this app run on Arch Linux and for some reason it won't let Me run it

[Version of Arch]
![image](https://user-images.githubusercontent.com/51787264/155063061-1a8eb61f-abfa-463f-8e7c-be2d085c3d81.png)

[Error]
![image](https://user-images.githubusercontent.com/51787264/155063152-90143665-6ab0-4a9e-962d-d13b4063bbe1.png)

**Comment by rrrogalski** [comment]
It worked for me altho on Gentoo, but I was running the same kernel. I ran it as the proper root user, not sure if that would make any difference. 

Does the same error come up when running `ps4fancontrol --no-gui`?

**Comment by Harleythetech** [comment]
Yes it does the same :D 
Also when i boot arch linux it also shows that the ps4fancontrol failed to start 
![image](https://user-images.githubusercontent.com/51787264/155483870-cf8642d0-07f5-4794-9bec-cb5bec3f9a21.png)

**Comment by Ps3itaTeam** [comment]
> I'm trying to make this app run on Arch Linux and for some reason it won't let Me run it
> 
> [Version of Arch] ![image](https://user-images.githubusercontent.com/51787264/155063061-1a8eb61f-abfa-463f-8e7c-be2d085c3d81.png)
> 
> [Error] ![image](https://user-images.githubusercontent.com/51787264/155063152-90143665-6ab0-4a9e-962d-d13b4063bbe1.png)

Can you please check if in the the file /etc/passwd do you have a line similar to this: `yourUserName:x:1000:1000::/home/yourUserName:/bin/bash`

**Comment by Harleythetech** [comment]
ah the version of arch that i used didn't have that. i'll leave this open for now since im testing a new manjaro (steamdeck by nazky) to see if this will work also

**Comment by Harleythetech** [comment]
Ok Got Back from testing Manjaro / Steamdeck OS 3.0 and i can safely say it works there and that i'll be closing this issue. 
Thanks for the Help Guys!
